language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2

branches:
  only:
    - master

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo -H bash ./script/install_dependencies_linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]  ; then bash ./script/install_dependencies_mac.sh          ; fi

script:
  - mkdir build
  - cd build
  - cmake -DTEST_ON=true -DUSE_CAFFE=true -DUSE_GIE=false -DUSE_MXNET=false -DUSE_FP16=false -DCPU_ONLY=true ..
  - make -j4
  - make -j4 test