language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      # Building on mac is too time consuming
      # - os: osx
      # osx_image: xcode7.2
  exclude:
    - os: linux
      dist: precise

branches:
  only:
    - master

cache:
  apt: true
  directories:
    - $HOME/installed_${TRAVIS_OS_NAME}
    - $HOME/installed_${TRAVIS_OS_NAME}/caffe-${CAFFE_COMMIT_HASH}

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash ./script/install_dependencies_linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]  ; then bash ./script/install_dependencies_mac.sh  ; fi

script:
  - mkdir build
  - cd build
  - echo $HOME/installed
  - cmake -DTEST_ON=true -DUSE_CAFFE=true -DUSE_GIE=false -DUSE_MXNET=false -DUSE_FP16=false -DBACKEND=cpu -DCAFFE_HOME=$(pwd)/../caffe/distribute ..
  - make -j4
  - make -j4 tests
  - ctest -V # -j will cause port being used problem
